# ============================================================
# Lesson 1 - Temporary Runner Example
# File: tempCodeRunnerFile.py
# Purpose: Quick route test (generated by editor during run)
# ============================================================

from flask import Flask

app = Flask(__name__)

# Same function is mapped to two URLs: / and /home
@app.route("/")
@app.route("/home")
def home():
    return "Welcome to Flask"

if __name__ == "__main__":
    app.run(debug=True)